### ISSUE TITLE
HTTP Error 502.5 - Process Failure

### ISSUE THREAD

**Issue by CG-Tespy** [PacktPublishing/ASP.NET-Core-3-and-Angular-9-Third-Edition#11]
I was following the instructions in the main page's Important Note section, except for running the npm-update.bat file, which wasn't anywhere in the repo. I just ran npm update through cmd instead.

Upon running the project in Debug Mode, I got the error noted in this issue's title. Since npm told me there were vulnerabilities, I then decided to run npm audit fix. Upon running the project again, the issue was still there.

This was when I ran the project in Visual Studio 2017. When I ran it with VS 2019, the error was instead was" TimeoutException: The Angular CLI process did not start listening for requests within the timeout period of 0 seconds. Check the log output for error information."

Here's everything in the Stack output:
Microsoft.AspNetCore.SpaServices.Extensions.Util.TaskTimeoutExtensions.WithTimeout<T>(Task<T> task, TimeSpan timeoutDelay, string message)
Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task<Uri> baseUriTask, CancellationToken applicationStoppingToken, bool proxy404s)
Microsoft.AspNetCore.Builder.SpaProxyingExtensions+<>c__DisplayClass2_0+<<UseProxyToSpaDevelopmentServer>b__0>d.MoveNext()
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by Darkseal** [comment]
Are you 100% sure that you have updated Angular 9  and Visual Studio 2019 to the versions specified in the book? It e who was happening to me as well before some recent fix.

try changing `"start": "ng serve"` to `"start": "echo Starting... && ng serve"` in the package.json file and tell me if you manage to fix it.

Also, take a look at this thread:
https://github.com/angular/angular-cli/issues/16961

**Comment by CG-Tespy** [comment]
After you added the update-npm.bat file, I redownloaded the repo and tried again. Once before running the file, and once after. The project worked :) Thank you very much, Darkseal

**Comment by Darkseal** [comment]
Wonderful :) Keep up the good work!

P.S.: If you like the book and you have a couple minutes to spare, don't forget to write a small review on Amazon: it will greatly help!
