### ISSUE TITLE
Issue page 320

### ISSUE THREAD

**Issue by OrbintSoft** [PacktPublishing/ASP.NET-Core-3-and-Angular-9-Third-Edition#22]
In the paper book, the file angular-material.component.ts is wrong, since it is a module and not a component.
The correct name should be: angular-material.module.ts.

**Comment by Darkseal** [comment]
Hi there,

I can confirm that it seems a cut-paste bug affecting paper version only: going to send this to Packt publishers so they can correct it in next prints.
