### ISSUE TITLE
Pg 108 ICMPHealthCheck.cs

### ISSUE THREAD

**Issue by JoeWaters1980** [PacktPublishing/ASP.NET-Core-3-and-Angular-9-Third-Edition#27]
www.does-not-exist.com does exist and will return a healthy check for all health checks. 
this will also need to be amended for all the health checks 
I simply used www.nothinghear.com

**Comment by Darkseal** [comment]
Yeah, someone registered the domain after I wrote the book :)

In the Fifth Edition we've fixed that: you can use a non-routable IP address such as 10.0.0.0 to permanently fix that

https://www.baeldung.com/cs/non-routable-ip-address
