### ISSUE TITLE
Upgrading Angular from 8 to 9

### ISSUE THREAD

**Issue by virshu** [PacktPublishing/ASP.NET-Core-3-and-Angular-9-Third-Edition#3]
Hello! Long time reader, first time commenter :)

When `dotnet` creates a new project based on Angular template, it scaffolds Angular 8 packages in package.json. If you update those packages to Angular 9, application stops working from Visual Studio 2019. It just hangs, and Angular portion never starts. And eventually it gives a timeout.

Microsoft has a whole page of suggestions for this situation: https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-3.1&tabs=visual-studio . Among other things, it recommends starting Angular application manually, and then changing in `UseSpa()` 

`spa.UseAngularCliServer(npmScript: "start");`
to 
`spa.UseProxyToSpaDevelopmentServer("http://localhost:4200");`

However, I am pleasantly surprised that *your* example of chapter 1 works out of the box! You don't even have the change in `UseSpa` ( _obviously_, since you don't need to start Angular manually). Unfortunately, your initial commit is already Angular 9.RC - so it's not exactly the application that `dotnet` generates.

So I am intrigued - what did you do to make your application work directly from Visual Studio?

**Comment by virshu** [comment]
UPDATE: I figured out how to do it based on this thread: https://jasontaylor.dev/asp-net-core-angular-9-upgrade/ - essentially, define `"start": "echo Starting... && ng serve"`
But *you* don't do it! So, I am still curious, how were you able to make this work... but I got it work as well :)

**Comment by Darkseal** [comment]
Well, I remember that I had to use the "echo" for the Angular 9 initial releases (including all the RCs)... but that was fixed later on, so I could remove it.
